<template>
    <section>
        <!-- loading spinner -->
        <b-modal
            id="modal-danger"
            v-model="showContent"
            hide-footer
            hide-header
            centered
            class="b-modal"
        >
            <div v-if="showContent">
                <div class="d-block text-center">
                    <h3>
                        {{ title }}
                    </h3>
                </div>
                <b-button
                    class="b-button"
                    variant="warning"
                    block
                    @click="
                        clickedNo;
                        showModal = !showModal;
                    "
                    >Нет</b-button
                >
                <b-button
                    class="b-button"
                    variant="danger"
                    block
                    @click="
                        clickedYes;
                        showModal = !showModal;
                    "
                    >Да!</b-button
                >
            </div>
            <div
                v-if="showLoading"
                class="text-center  d-flex justify-content-center align-items-center loading__spinner"
            >
                <b-spinner :variant="'warning'" :key="'warning'"></b-spinner>
            </div>

            <div class="success__block" v-if="showSuccess">
                <div class="success__icon">
                    <svg
                        xml:space="preserve"
                        viewBox="0 0 100 100"
                        y="0"
                        x="0"
                        xmlns="http://www.w3.org/2000/svg"
                        id="圖層_1"
                        version="1.1"
                        width="200px"
                        height="200px"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        style="width:100%;height:100%;background-size:initial;background-repeat-y:initial;background-repeat-x:initial;background-position-y:initial;background-position-x:initial;background-origin:initial;background-color:initial;background-clip:initial;background-attachment:initial;animation-play-state:play"
                    >
                        <g
                            class="ldl-scale"
                            style="transform-origin:50% 50%;transform:rotate(0deg) scale(0.8, 0.8);animation-play-state:play"
                        >
                            <circle
                                stroke-miterlimit="10"
                                stroke-width="
						5"
                                stroke="#333"
                                fill="none"
                                r="40"
                                cy="50"
                                cx="50"
                                style="stroke:rgb(2, 48, 71);animation-play-state:play"
                            ></circle>
                            <g style="animation-play-state:play" class="exl">
                                <path
                                    d="M43.7 69.4L25 47.7l3.9-3.9 14.8 12.6 28.6-25.8 2.7 2.7z"
                                    fill="#abbd81"
                                    style="fill:rgb(247, 147, 31);animation-play-state:play"
                                ></path>
                            </g>
                            <metadata
                                xmlns:d="https://loading.io/stock/"
                                style="animation-play-state:play"
                            >
                                <d:name style="animation-play-state:play"
                                    >ok</d:name
                                >
                                <d:tags style="animation-play-state:play"
                                    >ok,confirm,ready,positive,check,right,correct,affirmative,success</d:tags
                                >
                                <d:license style="animation-play-state:play"
                                    >by</d:license
                                >
                                <d:slug style="animation-play-state:play"
                                    >47ibm8</d:slug
                                >
                            </metadata>
                        </g>
                        <!-- generated by https://loading.io/ -->
                    </svg>
                </div>
            </div>
        </b-modal>
    </section>
</template>

<script>
export default {
    props: ["title", "showModal", "showLoading", "showSuccess", "showContent"],
    data() {
        return {
            spinnerVariants: [
                "primary",
                "secondary",
                "danger",
                "warning",
                "success",
                "info",
                "light",
                "dark"
            ]
        };
    },

    methods: {
        clickedNo() {
            this.$emit("clickNo");
        },

        clickedYes() {
            this.$emit("clickYes");
        }
    }
};
</script>

<style lang="scss" scoped>
#modal-danger___BV_modal_body_ {
    .loading__spinner {
        min-height: 80px;
    }

    .success__block {
        min-height: 80px;
        width: 100%;
        z-index: 9999;
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;

        .success__icon {
            max-width: 80%;
            width: 80px;
            animation: scaleIcon 1.3s infinite linear forwards;
            color: #155724;
            border-color: #c3e6cb;
            border-radius: 4px;
            padding: 3px 8px;

            display: flex;

            justify-content: center;
            align-items: center;
            overflow: hidden;
        }
    }

    @keyframes scaleIcon {
        0% {
            transform: scale(1);
        }
        25% {
            transform: scale(0.9);
        }
        50% {
            transform: scale(1);
        }
        75% {
            transform: scale(1.08);
        }
        100% {
            transform: scale(1);
        }
    }

    // --------------------
    div > h3 {
        font-size: 20px;
    }
    button {
        font-size: 12px;
    }
    button:first-of-type {
        margin-top: 20px;
    }

    .input__box {
        flex-grow: 0;
        height: auto;

        &:not(:first-of-type) {
            margin-top: 10px;
        }
        label {
            font-family: Roboto, sans-serif;
            font-size: 14px;
            line-height: 24px;
            margin: 0;
            padding: 4px 0;
        }

        input,
        textarea {
            border: 0.98px solid #f7931e;
            box-sizing: border-box;
            border-radius: 5px;

            font-size: 18px;
            line-height: 1.3;

            cursor: pointer;
        }

        .input__file,
        .input__file__label {
            padding: 4px 0;
            display: inline-block;
            border: none;
            margin-right: 10px;
            font-size: 14px;
            line-height: 1;

            margin: 5px 5px 5px 0;
        }

        .input__file__label {
            font-size: 16px;
        }

        textarea {
            padding-top: 10px;
        }
        .form-control:focus {
            color: #495057;
            background-color: #fff;
            border-color: #f7931e;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(247, 147, 30, 0.25);
        }
    }
    div > a {
        cursor: pointer;
    }
}

// Flexible modal
@media only screen and (max-width: 440px) {
    #modal-danger___BV_modal_body_ {
        div > h3 {
            font-size: 18px;
        }
        button {
            display: inline-block;
            width: 45%;
            font-size: 10px;
            margin-top: 15px !important;
        }
        .success__block {
            .success__icon {
                max-width: 70%;
                width: 80px;
            }
        }
    }
}
</style>
